elasticsearch:
  host: localhost
  port: 9200
  index: mudf_benchmark
postgresql:
  host: localhost
  port: 5432
  database: mudf_benchmark
  user: postgres
  password: postgres
mongodb:
  host: localhost
  port: 27017
  database: mudf_benchmark
  user: admin
  password: password
